import:
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-base-r4.0.yml
jobs:
  include:
    - stage: test
      name: dom0-fc25
      env: DIST_DOM0=fc25 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 VERBOSE=0 TRAVIS_INSTALL_EXCLUDE="xen-qubes-vm"
    - stage: test
      name: vm-fc31
      env: DISTS_VM=fc30 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 VERBOSE=0 TRAVIS_INSTALL_EXCLUDE="xen-qubes-debug xen-qubes-debuginfo xen-qemu-tools xen"
    - stage: test
      name: vm-fc32
      env: DISTS_VM=fc31 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 VERBOSE=0 TRAVIS_INSTALL_EXCLUDE="xen-qubes-debug xen-qubes-debuginfo xen-qemu-tools xen"
    - stage: test
      name: vm-stretch
      env: DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 TRAVIS_INSTALL_EXCLUDE="xen-hypervisor-common xen-system-amd64"
    - stage: test
      name: vm-buster
      env: DISTS_VM=buster USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 TRAVIS_INSTALL_EXCLUDE="xen-hypervisor-common xen-system-amd64"
    - stage: test
      name: vm-bullseye
      env: DISTS_VM=bullseye USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1 TRAVIS_INSTALL_EXCLUDE="xen-hypervisor-common xen-system-amd64"
